### ISSUE TITLE
Figure out what the question marks are in state tracker

### ISSUE THREAD

**Issue by timathomas** [evictionresearch/evictionresearch.github.io#25]

**Comment by JuliaGreenberg1** [comment]
Fill in state coverage column of [state tracker](https://docs.google.com/spreadsheets/d/157ns-6jlzBzK0QD3ECDhSoEqUvis1PfhrVrtYpFkoJY/edit#gid=0)

**Comment by JuliaGreenberg1** [comment]
@timathomas Here are the states that we need to fill in the ???s in the state tracker for:

- colorado
- kansas
- kentucky
- puerto rico
- alaska
- hawaii
- virgin islands
- maine
- new hampshire
- new york
- utah
- wisconsin

It looks like `ucb_cases.qs` (in `/accounts/projects/timthomas/udp/data/evictionresearch/lsc/raw`) only includes data for kansas, puerto rico, alaska, virgin islands, and utah. When I use your code (see chunk below) from `lsc/code/d1_data_prep.r` to `left_join` `ucb_parties.qs` with `ucb_cases.qs`, the resulting dataframe (`def`) restricts these states even further, to only the virgin islands. Is there a different dataset I should be downloading that includes all these states listed above? I'm confused because these two are downloaded directly from Google Drive so I'm not sure why they would be missing so many states. I also don't understand why `ucb_cases.qs` contains data for kansas, puerto rico, alaska and utah but `ucb_parties.qs` does not.

```
def <-
  parties %>%
  mutate(good_tract =
    case_when(addr_type %in% c("PointAddress", "StreetAddress", "StreetAddressExt", "StreetInt", "StreetName", "Subaddress") & score >= .85 ~ 1, TRUE ~0
    )
  ) %>%
  group_by(case_key) %>%
  filter(grepl("def", party_type)) %>%
  slice(1) %>%
  ungroup() %>%
  left_join(cases) %>%
  mutate(year = year(date_filed), month = month(date_filed)) %>%
  arrange(case_key, desc(year)) %>%
  group_by(case_key) %>% # pick last year of filing
  slice(1) %>%
  glimpse()
```

**Comment by timathomas** [comment]
@JuliaGreenberg1 I'll work on this.

**Comment by JuliaGreenberg1** [comment]
@timathomas ok let me know how I can help -- if you figure out which file(s) contain the states we need I can definitely explore the geographic coverage
